# Generated by Django 2.2 on 2021-06-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='Pizza_App.User'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pizza', to='Pizza_App.Order'),
        ),
        migrations.AlterField(
            model_name='purchased_pizza',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pizza', to='Pizza_App.Purchased_Order'),
        ),
    ]
