# Generated by Django 2.2 on 2021-06-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0002_auto_20210611_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('orderPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempOrders', to='Pizza_App.User')),
            ],
        ),
        migrations.CreateModel(
            name='tempPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('crust', models.CharField(max_length=20)),
                ('toppings', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempPizza', to='Pizza_App.tempOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchased_pizza',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Pizza_App.User'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempPizza', to='Pizza_App.Order'),
        ),
        migrations.DeleteModel(
            name='Purchased_Order',
        ),
        migrations.DeleteModel(
            name='Purchased_Pizza',
        ),
    ]
